version: '3.3'

services:
  config-server:
    ports:
        - "9000:9000"   
    expose:
        - 9000
    build:
      context: config-server
      dockerfile: server.dockerfile 
    networks:
       - network1
  library-client:
    ports:
        - "8000:8000"
    expose:
        - 8000
    build:
      context: book
      dockerfile: book.dockerfile
    depends_on:
      - "config-server"
    networks:
       - network1
networks:
  network1:
    driver: bridge