version: '3.3'

services:
  config-server:
    expose:
        - 9000
    build:
      context: config-server
      dockerfile: server.dockerfile 
    networks:
      - network1
    environment: &environment
      - EUREKA_ADDRESS=eureka-server:8090
    depends_on:
      - "eureka-server"
  library-client:
    ports:
      - "8000:8000"
    expose:
      - 8000
    build:
      context: book
      dockerfile: book.dockerfile
    depends_on:
      - "eureka-server"
      - "config-server"
    networks:
      - network1
    environment:
      - EUREKA_ADDRESS=eureka-server:8090
  eureka-server:
    ports:
      - "8090:8090"
    expose:
      - 8090
    build:
      context: eureka-server
      dockerfile: eureka.dockerfile
    networks:
      - network1
    environment:
      - EUREKA_ADDRESS=eureka-server:8090
networks:
  network1:
    driver: bridge